# Generated by Django 5.1.4 on 2025-03-19 09:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'Kunde'), ('business', 'Anbieter')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid username. Only letters, numbers, spaces, and @/./+/-/_ are allowed.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
